### ISSUE TITLE
Requesting a removed language should not answer in that language

### ISSUE THREAD

**Issue by francoisno** [theopenconversationkit/tock#1062]
Currently requesting a bot on a language, which has been removed from the application, may result in an answer in that language.
Instead, the bot should respond in another supported language (or maybe throw an error?).

Also see #1063

**Comment by vsct-jburet** [comment]
When you delete a language in Tock Studio AND the language is requested in the bot app, the bot has cache the old app and with the old language - so the deleted language seems valid. 

The issue is that the bot does not have access to the nlp app database, so is not able to listen app definition changes. 
I 'm going to fix the bug by storing the locales in the bot configuration definition - and listen for the changes - this will also allow to manage the locales by bot configurations
