### ISSUE TITLE
Import label.json/CSV KO

### ISSUE THREAD

**Issue by Snylwen** [theopenconversationkit/tock#1067]
Tock version: build-20.9.1-0 

It's not anymore possible to import label (Json/CSV) file.
The .csv extension is not supported.
The .json extension is authorized however when the file is uploaded, nothing appear after the import.

![screenshot-botinoui-develop1-admin sncfvoyages-dev aws vsct fr-2020 10 15-14_15_26](https://user-images.githubusercontent.com/72923777/96121848-e6ad7780-0ef0-11eb-9be8-924b49c2b497.png)

![screenshot-botinoui-develop1-admin sncfvoyages-dev aws vsct fr-2020 10 15-14_19_49](https://user-images.githubusercontent.com/72923777/96122290-8cf97d00-0ef1-11eb-8ce2-518911410dbf.png)

Note : 
The pop-up following message don't check if the task or file is successfull imported. 
(Test : Change the csv by Json extension and it's display the import was done)
![screenshot-botinoui-develop1-admin sncfvoyages-dev aws vsct fr-2020 10 15-14_23_47](https://user-images.githubusercontent.com/72923777/96122662-1dd05880-0ef2-11eb-8518-c18c47b14524.png)

**Comment by francoisno** [comment]
JS console error reveals the `[uploader]="uploader"` is missing in HTML file `input` since the `I18nImportComponent` refactoring (june). But other things seem broken : e.g. CSV imports result in requests to the admin server layer (`/i18n/import/csv`), but JSON imports trigger no request (to `/i18n/import/json`).
