### ISSUE TITLE
Impossible to upload a csv file from Tock Studio

### ISSUE THREAD

**Issue by pi-2r** [theopenconversationkit/tock#1167]
Hello @broxmik,

In the tab "Stories & Answers" => "Answers", it's impossible to upload a CSV file (the json works very well) from Google Chrome or Firefox browser.
![image](https://user-images.githubusercontent.com/2684587/105374458-0519c200-5c08-11eb-9ae4-690130397b04.png)

For information, the bug is present on version 20.9.1
note: json and csv export works correctly.

Best regards,
Pierre

**Comment by francoisno** [comment]
Hi @pi-2r,
Could you precise the Tock version you use ? _(Tips: build/commit is visible hovering the (i) icon on each Tock Studio page)_
CSV labels import was fixed by #1067 released in Tock `20.9.1` (https://github.com/theopenconversationkit/tock/milestone/31?closed=1).
However, the import dialog should include some text (see the screenshot below), which makes me wonder the version you actually have.
Please let me know

![Capture d’écran du 2021-02-14 18-31-15](https://user-images.githubusercontent.com/7584800/107884044-dfc06100-6ef2-11eb-9045-0316983d5669.png)

**Comment by francoisno** [comment]
Hi @pi-2r any update on this issue?
